package com.example.myapplication.highSchool.sophomore;

import androidx.appcompat.app.AppCompatActivity;

import com.example.myapplication.Word;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class sophomorewordlist extends AppCompatActivity {
    private static List<Word> wordList = new ArrayList<>();

    static {
        wordList.add(new Word("abandon", "버리다, 포기하다"));
        wordList.add(new Word("able", "할 수 있는"));
        wordList.add(new Word("abnormal", "비정상적인"));
        wordList.add(new Word("absence", "결석, 부재"));
        wordList.add(new Word("absolute", "절대적인"));
        wordList.add(new Word("absorb", "흡수하다"));
        wordList.add(new Word("abuse", "남용하다, 학대하다"));
        wordList.add(new Word("academic", "학문적인"));
        wordList.add(new Word("accent", "강세, 억양"));
        wordList.add(new Word("accept", "받다, 수락하다"));
        wordList.add(new Word("access", "접근, 접근하다"));
        wordList.add(new Word("accident", "사고"));
        wordList.add(new Word("accompany", "동반하다, 함께 가다"));
        wordList.add(new Word("accomplish", "성취하다"));
        wordList.add(new Word("according", "따르는, ~에 의한"));
        wordList.add(new Word("accurate", "정확한"));
        wordList.add(new Word("accuse", "비난하다"));
        wordList.add(new Word("achieve", "성취하다"));
        wordList.add(new Word("acquire", "얻다, 습득하다"));
        wordList.add(new Word("address", "주소, 연설하다"));
        wordList.add(new Word("advance", "진보, 발전하다"));
        wordList.add(new Word("advice", "충고"));
        wordList.add(new Word("affect", "영향을 미치다"));
        wordList.add(new Word("afford", "여유가 있다, ~할 여유가 있다"));
        wordList.add(new Word("against", "~에 반대하여"));
        wordList.add(new Word("agency", "대행사"));
        wordList.add(new Word("aggressive", "공격적인"));
        wordList.add(new Word("ahead", "앞서, 미리"));
        wordList.add(new Word("alcohol", "알콜"));
        wordList.add(new Word("allege", "주장하다"));
        wordList.add(new Word("allow", "허락하다"));
        wordList.add(new Word("almost", "거의"));
        wordList.add(new Word("already", "이미"));
        wordList.add(new Word("amazing", "놀라운"));
        wordList.add(new Word("among", "~중에, ~사이에"));
        wordList.add(new Word("analysis", "분석"));
        wordList.add(new Word("ancient", "고대의"));
        wordList.add(new Word("anger", "분노"));
        wordList.add(new Word("animal", "동물"));
        wordList.add(new Word("annual", "연간의"));
        wordList.add(new Word("anxiety", "불안"));
        wordList.add(new Word("apology", "사과"));
        wordList.add(new Word("approve", "승인하다"));
        wordList.add(new Word("argue", "논쟁하다"));
        wordList.add(new Word("arrival", "도착"));
        wordList.add(new Word("article", "기사, 항목"));
        wordList.add(new Word("artist", "예술가"));
        wordList.add(new Word("attempt", "시도하다"));
        wordList.add(new Word("average", "평균"));
        wordList.add(new Word("aware", "알고 있는"));
        wordList.add(new Word("benefit", "이익"));
        wordList.add(new Word("bother", "괴롭히다"));
        wordList.add(new Word("brilliant", "훌륭한, 빛나는"));
        wordList.add(new Word("calm", "진정한, 침착한"));
        wordList.add(new Word("camera", "카메라"));
        wordList.add(new Word("capital", "수도"));
        wordList.add(new Word("careful", "조심스러운"));
        wordList.add(new Word("celebrate", "축하하다"));
        wordList.add(new Word("century", "세기"));
        wordList.add(new Word("certain", "확실한"));
        wordList.add(new Word("change", "변화, 바꾸다"));
        wordList.add(new Word("charge", "요금, 요금하다"));
        wordList.add(new Word("chronic", "만성적인"));
        wordList.add(new Word("circumstance", "상황"));
        wordList.add(new Word("citizen", "시민"));
        wordList.add(new Word("climate", "기후"));
        wordList.add(new Word("combine", "결합하다"));
        wordList.add(new Word("comment", "논평"));
        wordList.add(new Word("common", "공통의, 일반적인"));
        wordList.add(new Word("complete", "완전한, 완료하다"));
        wordList.add(new Word("complex", "복잡한"));
        wordList.add(new Word("confirm", "확인하다"));
        wordList.add(new Word("conflict", "갈등"));
        wordList.add(new Word("conscious", "의식적인"));
        wordList.add(new Word("contribute", "기여하다"));
        wordList.add(new Word("control", "제어하다"));
        wordList.add(new Word("convince", "설득하다"));
        wordList.add(new Word("cooperate", "협력하다"));
        wordList.add(new Word("corrupt", "부패한"));
        wordList.add(new Word("create", "창조하다"));
        wordList.add(new Word("culture", "문화"));
        wordList.add(new Word("curious", "호기심 많은"));
        wordList.add(new Word("damage", "손상"));
        wordList.add(new Word("danger", "위험"));
        wordList.add(new Word("decide", "결정하다"));
        wordList.add(new Word("define", "정의하다"));
        wordList.add(new Word("delicate", "섬세한"));
        wordList.add(new Word("describe", "묘사하다"));
        wordList.add(new Word("demand", "요구하다"));
        wordList.add(new Word("deny", "부인하다"));
        wordList.add(new Word("depend", "의존하다"));
        wordList.add(new Word("different", "다른"));
        wordList.add(new Word("difficult", "어려운"));
        wordList.add(new Word("discovery", "발견"));
        wordList.add(new Word("disease", "질병"));
        wordList.add(new Word("distance", "거리"));
        wordList.add(new Word("document", "문서"));
        wordList.add(new Word("dominate", "지배하다"));
        wordList.add(new Word("doubt", "의심"));
        wordList.add(new Word("drastic", "극단적인"));
        wordList.add(new Word("effect", "효과"));
        wordList.add(new Word("efficient", "효율적인"));
        wordList.add(new Word("emergency", "비상 상황"));
        wordList.add(new Word("emphasize", "강조하다"));
        wordList.add(new Word("enjoy", "즐기다"));
        wordList.add(new Word("enough", "충분한"));
        wordList.add(new Word("enthusiastic", "열광적인"));
        wordList.add(new Word("escape", "탈출하다"));
        wordList.add(new Word("essential", "필수적인"));
        wordList.add(new Word("estimate", "추정하다"));
        wordList.add(new Word("evidence", "증거"));
        wordList.add(new Word("examine", "조사하다"));
        wordList.add(new Word("example", "예시"));
        wordList.add(new Word("excuse", "변명, 용서하다"));
        wordList.add(new Word("experience", "경험"));
        wordList.add(new Word("expand", "확장하다"));
        wordList.add(new Word("expect", "기대하다"));
        wordList.add(new Word("explain", "설명하다"));
        wordList.add(new Word("failure", "실패"));
        wordList.add(new Word("feature", "특징"));
        wordList.add(new Word("fiction", "소설"));
        wordList.add(new Word("fortunate", "행운의"));
        wordList.add(new Word("frustrate", "좌절시키다"));
        wordList.add(new Word("further", "더 나아가"));
        wordList.add(new Word("generous", "관대한"));
        wordList.add(new Word("genuine", "진짜의"));
        wordList.add(new Word("govern", "통치하다"));
        wordList.add(new Word("habit", "습관"));
        wordList.add(new Word("harmony", "조화"));
        wordList.add(new Word("ability", "능력"));
        wordList.add(new Word("absorb", "흡수하다"));
        wordList.add(new Word("abundant", "풍부한"));
        wordList.add(new Word("accept", "받아들이다"));
        wordList.add(new Word("accurate", "정확한"));
        wordList.add(new Word("achieve", "성취하다"));
        wordList.add(new Word("active", "활동적인"));
        wordList.add(new Word("adapt", "적응하다"));
        wordList.add(new Word("admire", "존경하다, 감탄하다"));
        wordList.add(new Word("admit", "인정하다, 입장을 허가하다"));
        wordList.add(new Word("advantage", "이점, 장점"));
        wordList.add(new Word("affect", "영향을 미치다"));
        wordList.add(new Word("afford", "여유가 되다"));
        wordList.add(new Word("against", "~에 반대하여"));
        wordList.add(new Word("agree", "동의하다"));
        wordList.add(new Word("alarm", "경보, 놀람"));
        wordList.add(new Word("allow", "허락하다"));
        wordList.add(new Word("alternative", "대안, 대체의"));
        wordList.add(new Word("amaze", "놀라게 하다"));
        wordList.add(new Word("analyze", "분석하다"));
        wordList.add(new Word("announce", "발표하다"));
        wordList.add(new Word("anxious", "걱정하는, 불안한"));
        wordList.add(new Word("appear", "나타나다, ~인 것처럼 보이다"));
        wordList.add(new Word("appoint", "임명하다, 지정하다"));
        wordList.add(new Word("appreciate", "감사하다, 감상하다"));
        wordList.add(new Word("appropriate", "적절한"));
        wordList.add(new Word("argue", "논쟁하다, 주장하다"));
        wordList.add(new Word("arrange", "정리하다, 준비하다"));
        wordList.add(new Word("arrive", "도착하다"));
        wordList.add(new Word("assist", "돕다"));
        wordList.add(new Word("assume", "추정하다, 가정하다"));
        wordList.add(new Word("attempt", "시도하다"));
        wordList.add(new Word("attend", "참석하다"));
        wordList.add(new Word("attract", "끌다, 유혹하다"));
        wordList.add(new Word("available", "이용 가능한"));
        wordList.add(new Word("average", "평균, 보통의"));
        wordList.add(new Word("avoid", "피하다"));
        wordList.add(new Word("benefit", "이익, 혜택"));
        wordList.add(new Word("behave", "행동하다"));
        wordList.add(new Word("belong", "속하다"));
        wordList.add(new Word("blame", "비난하다, 책임"));
        wordList.add(new Word("borrow", "빌리다"));
        wordList.add(new Word("brief", "간결한"));
        wordList.add(new Word("bright", "밝은, 영리한"));
        wordList.add(new Word("bury", "묻다, 매장하다"));
        wordList.add(new Word("calculate", "계산하다"));
        wordList.add(new Word("capable", "능력이 있는"));
        wordList.add(new Word("career", "직업, 경력"));
        wordList.add(new Word("careful", "조심스러운"));
        wordList.add(new Word("celebrate", "축하하다"));
        wordList.add(new Word("challenge", "도전"));
        wordList.add(new Word("character", "성격, 등장인물"));
        wordList.add(new Word("charge", "요금, 책임, 충전하다"));
        wordList.add(new Word("cheerful", "쾌활한"));
        wordList.add(new Word("circumstance", "환경, 상황"));
        wordList.add(new Word("claim", "주장하다"));
        wordList.add(new Word("collect", "모으다"));
        wordList.add(new Word("combine", "결합하다"));
        wordList.add(new Word("comfort", "위로, 편안함"));
        wordList.add(new Word("common", "일반적인, 공통의"));
        wordList.add(new Word("communicate", "의사소통하다"));
        wordList.add(new Word("community", "공동체"));
        wordList.add(new Word("compare", "비교하다"));
        wordList.add(new Word("complain", "불평하다"));
        wordList.add(new Word("complete", "완전한, 완료하다"));
        wordList.add(new Word("complicated", "복잡한"));
        wordList.add(new Word("concentrate", "집중하다"));
        wordList.add(new Word("concern", "걱정, 관심사"));
        wordList.add(new Word("conclude", "결론을 내리다"));
        wordList.add(new Word("confirm", "확인하다"));
        wordList.add(new Word("connect", "연결하다"));
        wordList.add(new Word("consider", "고려하다"));
        wordList.add(new Word("contain", "포함하다"));
        wordList.add(new Word("continue", "계속하다"));
        wordList.add(new Word("contrast", "대조, 차이"));
        wordList.add(new Word("contribute", "기여하다, 공헌하다"));
        wordList.add(new Word("control", "통제하다"));
        wordList.add(new Word("convenient", "편리한"));
        wordList.add(new Word("cooperate", "협력하다"));
        wordList.add(new Word("correct", "올바른, 수정하다"));
        wordList.add(new Word("count", "세다, 중요하다"));
        wordList.add(new Word("create", "창조하다"));
        wordList.add(new Word("curious", "호기심이 많은"));
        wordList.add(new Word("damage", "손상, 피해"));
        wordList.add(new Word("decrease", "감소하다"));
        wordList.add(new Word("defend", "방어하다"));
        wordList.add(new Word("define", "정의하다"));
        wordList.add(new Word("delay", "지연시키다, 연기하다"));
        wordList.add(new Word("delight", "기쁨, 즐겁게 하다"));
        wordList.add(new Word("demand", "요구하다, 수요"));
        wordList.add(new Word("deny", "부인하다"));
        wordList.add(new Word("depend", "의존하다"));
        wordList.add(new Word("describe", "묘사하다, 설명하다"));
        wordList.add(new Word("desire", "욕구, 바라다"));
        wordList.add(new Word("develop", "발전하다, 개발하다"));
        wordList.add(new Word("difference", "차이"));
        wordList.add(new Word("difficult", "어려운"));
        wordList.add(new Word("direct", "직접적인, 지시하다"));
        wordList.add(new Word("disappear", "사라지다"));
        wordList.add(new Word("discover", "발견하다"));
        wordList.add(new Word("discuss", "논의하다"));
        wordList.add(new Word("distance", "거리"));
        wordList.add(new Word("divide", "나누다"));
        wordList.add(new Word("domestic", "국내의, 가정의"));
        wordList.add(new Word("doubt", "의심하다, 의혹"));

    }

    public static List<Word> getShuffledWords() {
        List<Word> shuffledList = new ArrayList<>(wordList);
        Collections.shuffle(shuffledList);
        return shuffledList;
    }
}
